
name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "20.x"

      - name: install dependencies
        run: npm install

      - name: execute integration tests
        run: npm run test
         
   